### ISSUE TITLE
Issues with Python Version/Pandas

### ISSUE THREAD

**Issue by Leo-Creasey** [giuliospinozzi/arpir#2]
Hello! 

I'm trying to get ARPIR up and running for a RNA-seq pipeline I have. However I am getting stuck at a bit of an early stage. When I try to run my script, I get the error:

```
File "ARPIR/ARPIR.py", line 61
    print header, description, usage_example
               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(header, description, usage_example)?
```

I found that this error was because I was running the program with python3 rather then python2, so I edited my script so that it ran with python2 (python 2.7.18 to be exact) and it was unable to import pandas:

```
Traceback (most recent call last):
  File "ARPIR/ARPIR.py", line 5, in <module>
    import pandas as pd
ImportError: No module named pandas
```

I have tried to look for a version of pandas that will work but have not been able to install one.

Does anyone have any suggestions as to what I should do? I get the feeling there must be a way to get pandas to work but I have drawn a blank (I am trying to run my pipeline in ubuntu on WSL in case it is relevant. I imagine it is not ideal). 

Many Thanks

Leo

**Comment by Leo-Creasey** [comment]
I have managed to solve this issue. 

I believe it was due to the fact that my default python was 3.6. As the program was written in 2.7 it needs that version of pandas, however my environment was only trying to import the incompatible version of pandas for python 3. I resolved the issue by creating a virtual environment which had python 2.7 as the default. Instructions on how I did this are below.

Note: I did this on Ubuntu (within windows subsystem for linux, wsl).

First install virtualenv for python2 

`sudo apt install python2 virtualenv`

Next make and navigate to a new directory for the new virtual environment

`mkdir ~/.virtualenvs`
`cd ~/.virtualenvs`

Then create the virtual environment.

`virtualenv --python=python2 env`

To check that the environment is made, and with the desired version of python you can run this line.

`ls env/lib`

Finally, you can run enter the environment with this final line.

`source env/bin/activate`

This should put you in the virtual environment. Pandas can be install as you would other packages (pip install pandas, for example, although this may not be nessecary for the code to run), and then you can run the program. 

Hope this helps people :) . 

Leo
